# Tugas Mandiri Data Wrangling – Pertemuan 2
**Nama Mahasiswa :** Raja Aunurrahman
**NIM :** 25200023

**Kasus:** PT Nusantara Retail Mandiri – analisis kampanye kupon diskon akhir bulan.  
**Sumber data:** (1) CSV transaksi POS, (2) database CRM di Neon (PostgreSQL), (3) REST API logistik (mockapi.io).

In [22]:
import os
from datetime import datetime

import numpy as np
import pandas as pd
import requests
from sqlalchemy import create_engine, text

CSV_PATH = "/content/drive/MyDrive/Datasets/transaksi_pos.csv"

DB_URL = os.getenv(
    "NEON_DATABASE_URL",
    "postgresql+psycopg2://neondb_owner:npg_qM5kW2yIPGhl@ep-square-cherry-azhqrpzl-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
)

API_URL = os.getenv(
    "LOGISTIK_API_URL",
    "https://6abdcb7dc4d5ac5483011535.mockapi.io/api/v1/deliveries",
)

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 1. Ekstraksi Berkas File (CSV) – Divisi Kasir/POS

In [24]:
print("[INFO] Mengimpor berkas transaksi POS...")
df_transaksi = pd.read_csv(
    CSV_PATH,
    dtype={"order_id": str, "customer_id": str},
    parse_dates=["order_date"],
)

print(f"[OK] {len(df_transaksi):,} baris, {df_transaksi.shape[1]} kolom dimuat.")
print(df_transaksi.dtypes)
df_transaksi.head()

[INFO] Mengimpor berkas transaksi POS...
[OK] 250 baris, 11 kolom dimuat.
order_id                   object
customer_id                object
order_date         datetime64[ns]
store_id                   object
channel                    object
payment_method             object
coupon_code                object
item_count                  int64
subtotal                    int64
discount_amount             int64
total_amount                int64
dtype: object

       order_id customer_id          order_date   store_id  channel payment_method coupon_code  item_count  subtotal  discount_amount  total_amount
0  ORD-26090128       C0036 2026-09-01 11:53:09   ST-BDG01  Offline   Kartu Kredit         NaN           7    293000                0        293000
1  ORD-26090118       C0022 2026-09-01 12:11:13   ST-BDG01  Offline          Debit         NaN           8    462500                0        462500
2  ORD-26090214       C0035 2026-09-01 16:46:17   ST-SBY01  Offline          Debit         NaN           1   1113000                0       1113000
3  ORD-26090097       C0043 2026-09-01 21:09:36  ST-ONLINE   Online           QRIS         NaN           3   1388000                0       1388000
4  ORD-26090132       C0041 2026-09-01 21:30:02  ST-ONLINE   Online       E-Wallet         NaN           6    592000                0        592000

## 2. Koneksi & Kueri Database (SQL) – Divisi CRM / Membership (Neon PostgreSQL)

In [15]:
print("[INFO] Menghubungkan ke database CRM...")
engine = create_engine(DB_URL, pool_pre_ping=True)

with engine.connect() as conn:
    conn.execute(text("SELECT 1"))
print("[OK] Koneksi ke database berhasil.")

query_crm = """
    SELECT customer_id, customer_name, membership_tier, city
    FROM customers
    WHERE is_active = 1
"""
df_crm = pd.read_sql(text(query_crm), con=engine)
df_crm["customer_id"] = df_crm["customer_id"].astype(str)

print(f"[OK] {len(df_crm):,} pelanggan aktif diekstrak.")
df_crm.head()

[INFO] Menghubungkan ke database CRM...
[OK] Koneksi ke database berhasil.
[OK] 52 pelanggan aktif diekstrak.

  customer_id  customer_name membership_tier        city
0       C0001   Andi Purnama          Bronze     Bandung
1       C0002   Agus Purnama          Silver     Bandung
2       C0003  Citra Saputra          Silver     Jakarta
3       C0004   Bayu Siregar          Bronze    Surabaya
4       C0005    Andi Wijaya          Bronze  Yogyakarta

## 3. Konsumsi REST API & Normalisasi JSON – Mitra Ekspedisi Logistik

In [16]:
print("[INFO] Menarik data pengiriman dari REST API...")
response = requests.get(API_URL, timeout=15)
response.raise_for_status()
payload = response.json()

records = payload["results"] if isinstance(payload, dict) else payload
print(f"[OK] {len(records):,} record diterima. Contoh struktur nested (1 record):")
print(records[0])

[INFO] Menarik data pengiriman dari REST API...
[OK] 100 record diterima. Contoh struktur nested (1 record):
{'order_id': 'ORD-26090097', 'tracking_number': 'JNE7590302909', 'delivery_status': 'DELIVERED', 'courier': {'name': 'JNE', 'service': 'REG'}, 'destination': {'city': 'Jakarta', 'province': 'DKI Jakarta'}, 'id': '1', 'timeline': {'shipped_at': '2026-09-03T02:09:36', 'delivered_at': '2026-09-04T02:09:36'}}

In [17]:
df_logistik = pd.json_normalize(records)

df_logistik.columns = df_logistik.columns.str.replace(".", "_", regex=False)

df_logistik = df_logistik.drop(columns=["id"], errors="ignore")

df_logistik["order_id"] = df_logistik["order_id"].astype(str)
for col in ["timeline_shipped_at", "timeline_delivered_at"]:
    df_logistik[col] = pd.to_datetime(df_logistik[col], errors="coerce")

print(f"[OK] Hasil flatten: {df_logistik.shape[0]} baris, {df_logistik.shape[1]} kolom")
print(df_logistik.dtypes)
df_logistik.head()

[OK] Hasil flatten: 100 baris, 9 kolom
order_id                         object
tracking_number                  object
delivery_status                  object
courier_name                     object
courier_service                  object
destination_city                 object
destination_province             object
timeline_shipped_at      datetime64[ns]
timeline_delivered_at    datetime64[ns]
dtype: object

       order_id tracking_number delivery_status courier_name courier_service destination_city destination_province timeline_shipped_at timeline_delivered_at
0  ORD-26090097   JNE7590302909       DELIVERED          JNE             REG          Jakarta          DKI Jakarta 2026-09-03 02:09:36   2026-09-04 02:09:36
1  ORD-26090132   JNE6448324230      IN_TRANSIT          JNE             YES         Denpasar                 Bali 2026-09-02 18:30:02                   NaT
2  ORD-26090162    JT1207916194       DELIVERED  J&T Express              EZ           Malang           Jawa Timur 2026-09-03 08:36:35   2026-09-05 08:36:35
3  ORD-26090198   JNE4683585586       DELIVERED          JNE             REG         Semarang          Jawa Tengah 2026-09-03 13:43:45   2026-09-04 13:43:45
4  ORD-26090169   SIC4905874257       DELIVERED      SiCepat            BEST          Bandung           Jawa Barat 2026-09-03 14:07:12   2026-09-05 14:07:12

## 4. Integrasi Data Multi-Sumber (Merging)

**Pilihan join dan alasannya**

| Penggabungan | Tipe join | Alasan |
|---|---|---|
| `df_transaksi` → `df_crm` (kunci `customer_id`) | **LEFT** | Unit analisis adalah **transaksi**. Dengan `inner`, transaksi dari pelanggan nonaktif atau yang tidak terdaftar di CRM ikut terbuang, sehingga *total transaksi berkupon* menjadi lebih kecil dari kenyataan. Dengan `left`, semua transaksi tetap terhitung, dan profil loyalitasnya diisi `NaN` (dilabeli "tidak terdaftar / nonaktif" saat analisis). |
| hasil di atas → `df_logistik` (kunci `order_id`) | **LEFT** | Transaksi **Offline** (beli di toko) memang tidak punya pengiriman. Dengan `left`, transaksi tersebut tetap ada dengan status pengiriman kosong, bukan hilang. |

**Validasi kardinalitas:** `validate="m:1"` (banyak transaksi → satu pelanggan) dan `validate="1:1"` (satu transaksi → satu pengiriman) membuat pandas menghentikan proses bila ada kunci ganda yang menggandakan baris.

In [18]:
print("[INFO] Melakukan integrasi data multi-sumber...")

df_master_analisis = (
    df_transaksi
    .merge(df_crm, on="customer_id", how="left", validate="m:1")
    .merge(df_logistik, on="order_id", how="left", validate="1:1")
)

# Pastikan jumlah baris sama dengan transaksi sumber (tidak ada duplikasi/kehilangan)
assert len(df_master_analisis) == len(df_transaksi), "Jumlah baris berubah setelah merge!"

print(f"[OK] df_master_analisis: {df_master_analisis.shape[0]:,} baris x {df_master_analisis.shape[1]} kolom")
df_master_analisis.head()

[INFO] Melakukan integrasi data multi-sumber...
[OK] df_master_analisis: 250 baris x 22 kolom

,order_id,customer_id,order_date,store_id,channel,payment_method,coupon_code,item_count,subtotal,discount_amount,total_amount,customer_name,membership_tier,city,tracking_number,delivery_status,courier_name,courier_service,destination_city,destination_province,timeline_shipped_at,timeline_delivered_at
0,ORD-26090128,C0036,2026-09-01 11:53:09,ST-BDG01,Offline,Kartu Kredit,NaN,7,293000,0,293000,Budi Kusuma,Bronze,Bandung,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
1,ORD-26090118,C0022,2026-09-01 12:11:13,ST-BDG01,Offline,Debit,NaN,8,462500,0,462500,Andi Purnama,Gold,Denpasar,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
2,ORD-26090214,C0035,2026-09-01 16:46:17,ST-SBY01,Offline,Debit,NaN,1,1113000,0,1113000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
3,ORD-26090097,C0043,2026-09-01 21:09:36,ST-ONLINE,Online,QRIS,NaN,3,1388000,0,1388000,Utami Nugroho,Bronze,Jakarta,JNE7590302909,DELIVERED,JNE,REG,Jakarta,DKI Jakarta,2026-09-03 02:09:36,2026-09-04 02:09:36
4,ORD-26090132,C0041,2026-09-01 21:30:02,ST-ONLINE,Online,E-Wallet,NaN,6,592000,0,592000,Joko Kusuma,Bronze,Denpasar,JNE6448324230,IN_TRANSIT,JNE,YES,Denpasar,Bali,2026-09-02 18:30:02,NaT

## 5. Otomasi Kamus Data (Data Dictionary)

In [19]:
def generate_data_dictionary(df: pd.DataFrame, n_sample: int = 3) -> pd.DataFrame:
    """Hasilkan ringkasan metadata untuk setiap kolom DataFrame."""
    total = len(df)
    rows = []
    for col in df.columns:
        n_missing = int(df[col].isnull().sum())
        sample = df[col].dropna().unique()[:n_sample]
        rows.append({
            "Nama Kolom": col,
            "Tipe Data (dtype)": str(df[col].dtype),
            "Jumlah Missing": n_missing,
            "Persen Missing (%)": round(n_missing / total * 100, 2) if total else 0.0,
            "Jumlah Nilai Unik": int(df[col].nunique(dropna=True)),
            "Sampel Nilai": " | ".join(map(str, sample)) if len(sample) else "-",
        })
    return pd.DataFrame(rows)


kamus_df = generate_data_dictionary(df_master_analisis)
kamus_df.to_csv("kamus_data_hasil.csv", index=False, encoding="utf-8")
print("[OK] Kamus data disimpan ke kamus_data_hasil.csv")
kamus_df

[OK] Kamus data disimpan ke kamus_data_hasil.csv

               Nama Kolom Tipe Data (dtype)  Jumlah Missing  Persen Missing (%)  Jumlah Nilai Unik                                       Sampel Nilai
0                order_id            object               0                 0.0                250         ORD-26090128 | ORD-26090118 | ORD-26090214
1             customer_id            object               0                 0.0                 63                              C0036 | C0022 | C0035
2              order_date    datetime64[ns]               0                 0.0                250  2026-09-01 11:53:09 | 2026-09-01 12:11:13 | 20...
3                store_id            object               0                 0.0                  6                    ST-BDG01 | ST-SBY01 | ST-ONLINE
4                 channel            object               0                 0.0                  2                                   Offline | Online
5          payment_method            object               0                 0.0                  6                        Kartu Kredit | Debit | QRIS
6             coupon_code            object             160                64.0                  3                PAYDAY50K | AKHIRBULAN25 | GAJIAN10
7              item_count             int64               0                 0.0                  8                                          7 | 8 | 1
8                subtotal             int64               0                 0.0                244                          293000 | 462500 | 1113000
9         discount_amount             int64               0                 0.0                 17                                 0 | 50000 | 100000
10           total_amount             int64               0                 0.0                244                          293000 | 462500 | 1113000
11          customer_name            object              47                18.8                 49         Budi Kusuma | Andi Purnama | Utami Nugroho
12        membership_tier            object              47                18.8                  4                           Bronze | Gold | Platinum
13                   city            object              47                18.8                  9                       Bandung | Denpasar | Jakarta
14        tracking_number            object             150                60.0                100       JNE7590302909 | JNE6448324230 | JT1207916194
15        delivery_status            object             150                60.0                  4                  DELIVERED | IN_TRANSIT | RETURNED
16           courier_name            object             150                60.0                  4                        JNE | J&T Express | SiCepat
17        courier_service            object             150                60.0                  4                                     REG | YES | EZ
18       destination_city            object             150                60.0                 10                        Jakarta | Denpasar | Malang
19   destination_province            object             150                60.0                  9                    DKI Jakarta | Bali | Jawa Timur
20    timeline_shipped_at    datetime64[ns]             159                63.6                 91  2026-09-03 02:09:36 | 2026-09-02 18:30:02 | 20...
21  timeline_delivered_at    datetime64[ns]             183                73.2                 67  2026-09-04 02:09:36 | 2026-09-05 08:36:35 | 20...

## 6. Validasi Kualitas & Integritas (Automated Assertions)

In [20]:
assert df_master_analisis["order_id"].is_unique, "Fatal: Terdeteksi order_id duplikat!"

assert df_master_analisis["total_amount"].notnull().all(), "Fatal: total_amount ada yang kosong!"
assert (df_master_analisis["total_amount"] >= 0).all(), "Fatal: Ada nilai transaksi negatif!"

hari_ini = pd.Timestamp.now()
assert (df_master_analisis["order_date"] <= hari_ini).all(), "Fatal: Ada tanggal pesanan di masa depan!"

assert (
    df_master_analisis["subtotal"] - df_master_analisis["discount_amount"]
    == df_master_analisis["total_amount"]
).all(), "Fatal: total_amount != subtotal - discount_amount!"
assert (df_master_analisis.loc[df_master_analisis["coupon_code"].isnull(), "discount_amount"] == 0).all(), \
    "Fatal: Ada diskon tanpa kode kupon!"

print("[SUCCESS] Seluruh validasi data lulus!")

[SUCCESS] Seluruh validasi data lulus!

## 7. Jawaban atas Kebutuhan Bisnis (Head of Business Strategy)

In [21]:
df_kupon = df_master_analisis[df_master_analisis["coupon_code"].notnull()].copy()

print("=== 1. Total transaksi yang menggunakan kupon ===")
print(f"Jumlah transaksi berkupon : {len(df_kupon):,} dari {len(df_master_analisis):,} "
      f"({len(df_kupon) / len(df_master_analisis):.1%})")
print(f"Total nilai transaksi     : Rp {df_kupon['total_amount'].sum():,.0f}")
print(f"Total diskon diberikan    : Rp {df_kupon['discount_amount'].sum():,.0f}")

print("\nPer kode kupon:")
display(
    df_kupon.groupby("coupon_code")
    .agg(jumlah_transaksi=("order_id", "count"),
         total_nilai=("total_amount", "sum"),
         total_diskon=("discount_amount", "sum"))
    .sort_values("jumlah_transaksi", ascending=False)
)

print("\n=== 2. Profil loyalitas pelanggan pengguna kupon ===")
profil = (
    df_kupon["membership_tier"]
    .fillna("Tidak terdaftar / nonaktif")
    .value_counts()
    .rename_axis("membership_tier")
    .reset_index(name="jumlah_transaksi")
)
profil["persen"] = (profil["jumlah_transaksi"] / profil["jumlah_transaksi"].sum() * 100).round(1)
display(profil)

print("\n=== 3. Status pengiriman pesanan berkupon ===")
status = (
    df_kupon["delivery_status"]
    .fillna("Tanpa pengiriman (Offline)")
    .value_counts()
    .rename_axis("delivery_status")
    .reset_index(name="jumlah_pesanan")
)
display(status)

=== 1. Total transaksi yang menggunakan kupon ===
Jumlah transaksi berkupon : 90 dari 250 (36.0%)
Total nilai transaksi     : Rp 69,189,575
Total diskon diberikan    : Rp 5,590,425

Per kode kupon:

              jumlah_transaksi  total_nilai  total_diskon
coupon_code
GAJIAN10                    32     24506450       1414550
PAYDAY50K                   31     22781500       1550000
AKHIRBULAN25                27     21901625       2625875

=== 2. Profil loyalitas pelanggan pengguna kupon ===

              membership_tier  jumlah_transaksi  persen
0                      Bronze                38    42.2
1                      Silver                22    24.4
2  Tidak terdaftar / nonaktif                20    22.2
3                        Gold                 7     7.8
4                    Platinum                 3     3.3

=== 3. Status pengiriman pesanan berkupon ===

              delivery_status  jumlah_pesanan
0  Tanpa pengiriman (Offline)              58
1                   DELIVERED              18
2                  IN_TRANSIT              11
3                  PROCESSING               3